server:
  port: 5943

custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api

spring:
  application:
    name: hangeulbada
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  data:
    mongodb:
      uri: ${MONGODB_URI}

clova:
  ocr:
    secretkey: ${CLOVA_OCR_SECRETKEY}
    api:
      url: ${CLOVA_OCR_API_URL}
  tts:
    client:
      id: ${CLOVA_TTS_CLIENT_ID}
      secret: ${CLOVA_TTS_CLIENT_SECRET}

cloud:
  aws:
    s3:
      bucket:
        name: bada-static-bucket
        url: ${AWS_S3_BUCKET_URL}
        region: ap-northeast-2
      access:
        key: ${AWS_ACCESS_KEY}
        secret: ${AWS_SECRET_ACCESS_KEY}

python:
  api:
    url: ${AI_PY_URL}